FROM python:3.11
LABEL maintainer="Nazim Lala <nazimlala@microsoft.com>"
WORKDIR /code
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
EXPOSE 8000
ENTRYPOINT ["gunicorn", "app:app"]