name: Trigger auto deployment for container-app-utmrf35edwpje

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-utmrf35edwpje-AutoDeployTrigger-5b793466-682c-446a-aae3-421a1674547b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPUTMRF35EDWPJE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPUTMRF35EDWPJE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPUTMRF35EDWPJE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPUTMRF35EDWPJE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPUTMRF35EDWPJE_REGISTRY_PASSWORD }}
          containerAppName: container-app-utmrf35edwpje
          resourceGroup: pythonflaskquick9ac8
          imageToBuild: default/container-app-utmrf35edwpje:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


